from PySide6.QtCore import QObject, SignalInstance


class iDeviceMonitor(QObject):
    @property
    def OnDeviceAdded(self) -> SignalInstance: ...
    @property
    def OnDeviceRemoved(self) -> SignalInstance: ...
    @property
    def Ender(self) -> object: ...

    def _run(self): ...
    def start(self): ...
    def stop(self): ...
