from jAGFx.contracts.dependencyInjection import iDependency


class iInvoker(iDependency):
    def __init__(self, *args, **kwargs) -> None: ...

    def _doTask(self, item): ...

    def _invokerService(self): ...

    def _stopInvokerService(self): ...

    def __call__(self, func): ...
